// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	"github.com/alexmeli100/remit/transfer/pkg/endpoint"
	"github.com/alexmeli100/remit/transfer/pkg/grpc/pb"
	"github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	transfer grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.TransferServer {
	return &grpcServer{transfer: makeTransferHandler(endpoints, options[endpoint.Transfer])}
}
