// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notificator.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendConfirmEmailRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Link                 string   `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendConfirmEmailRequest) Reset()         { *m = SendConfirmEmailRequest{} }
func (m *SendConfirmEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendConfirmEmailRequest) ProtoMessage()    {}
func (*SendConfirmEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58946ae35107879d, []int{0}
}

func (m *SendConfirmEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendConfirmEmailRequest.Unmarshal(m, b)
}
func (m *SendConfirmEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendConfirmEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendConfirmEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendConfirmEmailRequest.Merge(m, src)
}
func (m *SendConfirmEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendConfirmEmailRequest.Size(m)
}
func (m *SendConfirmEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendConfirmEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendConfirmEmailRequest proto.InternalMessageInfo

func (m *SendConfirmEmailRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendConfirmEmailRequest) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *SendConfirmEmailRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type SendConfirmEmailReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendConfirmEmailReply) Reset()         { *m = SendConfirmEmailReply{} }
func (m *SendConfirmEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendConfirmEmailReply) ProtoMessage()    {}
func (*SendConfirmEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_58946ae35107879d, []int{1}
}

func (m *SendConfirmEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendConfirmEmailReply.Unmarshal(m, b)
}
func (m *SendConfirmEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendConfirmEmailReply.Marshal(b, m, deterministic)
}
func (m *SendConfirmEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendConfirmEmailReply.Merge(m, src)
}
func (m *SendConfirmEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendConfirmEmailReply.Size(m)
}
func (m *SendConfirmEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendConfirmEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendConfirmEmailReply proto.InternalMessageInfo

func (m *SendConfirmEmailReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type SendPasswordResetEmailRequest struct {
	Link                 string   `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPasswordResetEmailRequest) Reset()         { *m = SendPasswordResetEmailRequest{} }
func (m *SendPasswordResetEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendPasswordResetEmailRequest) ProtoMessage()    {}
func (*SendPasswordResetEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58946ae35107879d, []int{2}
}

func (m *SendPasswordResetEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPasswordResetEmailRequest.Unmarshal(m, b)
}
func (m *SendPasswordResetEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPasswordResetEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendPasswordResetEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPasswordResetEmailRequest.Merge(m, src)
}
func (m *SendPasswordResetEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendPasswordResetEmailRequest.Size(m)
}
func (m *SendPasswordResetEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPasswordResetEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPasswordResetEmailRequest proto.InternalMessageInfo

func (m *SendPasswordResetEmailRequest) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *SendPasswordResetEmailRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type SendPasswordResetEmailReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPasswordResetEmailReply) Reset()         { *m = SendPasswordResetEmailReply{} }
func (m *SendPasswordResetEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendPasswordResetEmailReply) ProtoMessage()    {}
func (*SendPasswordResetEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_58946ae35107879d, []int{3}
}

func (m *SendPasswordResetEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPasswordResetEmailReply.Unmarshal(m, b)
}
func (m *SendPasswordResetEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPasswordResetEmailReply.Marshal(b, m, deterministic)
}
func (m *SendPasswordResetEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPasswordResetEmailReply.Merge(m, src)
}
func (m *SendPasswordResetEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendPasswordResetEmailReply.Size(m)
}
func (m *SendPasswordResetEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPasswordResetEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendPasswordResetEmailReply proto.InternalMessageInfo

func (m *SendPasswordResetEmailReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type SendWelcomeEmailRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWelcomeEmailRequest) Reset()         { *m = SendWelcomeEmailRequest{} }
func (m *SendWelcomeEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendWelcomeEmailRequest) ProtoMessage()    {}
func (*SendWelcomeEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58946ae35107879d, []int{4}
}

func (m *SendWelcomeEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWelcomeEmailRequest.Unmarshal(m, b)
}
func (m *SendWelcomeEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWelcomeEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendWelcomeEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWelcomeEmailRequest.Merge(m, src)
}
func (m *SendWelcomeEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendWelcomeEmailRequest.Size(m)
}
func (m *SendWelcomeEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWelcomeEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendWelcomeEmailRequest proto.InternalMessageInfo

func (m *SendWelcomeEmailRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendWelcomeEmailRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type SendWelcomeEmailReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWelcomeEmailReply) Reset()         { *m = SendWelcomeEmailReply{} }
func (m *SendWelcomeEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendWelcomeEmailReply) ProtoMessage()    {}
func (*SendWelcomeEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_58946ae35107879d, []int{5}
}

func (m *SendWelcomeEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWelcomeEmailReply.Unmarshal(m, b)
}
func (m *SendWelcomeEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWelcomeEmailReply.Marshal(b, m, deterministic)
}
func (m *SendWelcomeEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWelcomeEmailReply.Merge(m, src)
}
func (m *SendWelcomeEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendWelcomeEmailReply.Size(m)
}
func (m *SendWelcomeEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWelcomeEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendWelcomeEmailReply proto.InternalMessageInfo

func (m *SendWelcomeEmailReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*SendConfirmEmailRequest)(nil), "pb.SendConfirmEmailRequest")
	proto.RegisterType((*SendConfirmEmailReply)(nil), "pb.SendConfirmEmailReply")
	proto.RegisterType((*SendPasswordResetEmailRequest)(nil), "pb.SendPasswordResetEmailRequest")
	proto.RegisterType((*SendPasswordResetEmailReply)(nil), "pb.SendPasswordResetEmailReply")
	proto.RegisterType((*SendWelcomeEmailRequest)(nil), "pb.SendWelcomeEmailRequest")
	proto.RegisterType((*SendWelcomeEmailReply)(nil), "pb.SendWelcomeEmailReply")
}

func init() {
	proto.RegisterFile("notificator.proto", fileDescriptor_58946ae35107879d)
}

var fileDescriptor_58946ae35107879d = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xcb, 0x2f, 0xc9,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a,
	0x48, 0x52, 0x0a, 0xe5, 0x12, 0x0f, 0x4e, 0xcd, 0x4b, 0x71, 0xce, 0xcf, 0x4b, 0xcb, 0x2c, 0xca,
	0x75, 0xcd, 0x4d, 0xcc, 0xcc, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62,
	0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x39,
	0x99, 0x79, 0xd9, 0x12, 0x4c, 0x10, 0x31, 0x10, 0x1b, 0x24, 0x96, 0x98, 0x92, 0x52, 0x24, 0xc1,
	0x0c, 0x11, 0x03, 0xb1, 0x95, 0x34, 0xb9, 0x44, 0x31, 0x8d, 0x2d, 0xc8, 0xa9, 0x14, 0x12, 0xe0,
	0x62, 0x4e, 0x2d, 0x2a, 0x82, 0x9a, 0x09, 0x62, 0x2a, 0xb9, 0x73, 0xc9, 0x82, 0x94, 0x06, 0x24,
	0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x04, 0xa5, 0x16, 0xa7, 0x96, 0xa0, 0xbb, 0x03, 0x6c, 0x27,
	0x23, 0x16, 0x3b, 0x99, 0x90, 0xec, 0xd4, 0xe7, 0x92, 0xc6, 0x65, 0x10, 0x76, 0x9b, 0x1d, 0x21,
	0x7e, 0x0f, 0x4f, 0xcd, 0x49, 0xce, 0xcf, 0x4d, 0x25, 0xc6, 0xef, 0x18, 0x76, 0x42, 0xfd, 0x89,
	0x6a, 0x04, 0x56, 0xdb, 0x8c, 0x9a, 0x99, 0xb8, 0xb8, 0xfd, 0x10, 0x71, 0x20, 0xe4, 0xc5, 0x25,
	0x80, 0x1e, 0x44, 0x42, 0xd2, 0x7a, 0x05, 0x49, 0x7a, 0x38, 0xe2, 0x43, 0x4a, 0x12, 0xbb, 0x24,
	0xc8, 0xb6, 0x18, 0x2e, 0x31, 0xec, 0x5e, 0x17, 0x52, 0x84, 0x69, 0xc2, 0x19, 0xbe, 0x52, 0xf2,
	0xf8, 0x94, 0x80, 0x4c, 0x87, 0xba, 0x14, 0xd9, 0x93, 0x08, 0x97, 0x62, 0x09, 0x3d, 0x84, 0x4b,
	0x31, 0xc2, 0x25, 0x89, 0x0d, 0x9c, 0xf4, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x98,
	0x45, 0xa0, 0x8f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NotificatorClient is the client API for Notificator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificatorClient interface {
	SendConfirmEmail(ctx context.Context, in *SendConfirmEmailRequest, opts ...grpc.CallOption) (*SendConfirmEmailReply, error)
	SendPasswordResetEmail(ctx context.Context, in *SendPasswordResetEmailRequest, opts ...grpc.CallOption) (*SendPasswordResetEmailReply, error)
	SendWelcomeEmail(ctx context.Context, in *SendWelcomeEmailRequest, opts ...grpc.CallOption) (*SendWelcomeEmailReply, error)
}

type notificatorClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificatorClient(cc grpc.ClientConnInterface) NotificatorClient {
	return &notificatorClient{cc}
}

func (c *notificatorClient) SendConfirmEmail(ctx context.Context, in *SendConfirmEmailRequest, opts ...grpc.CallOption) (*SendConfirmEmailReply, error) {
	out := new(SendConfirmEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notificator/SendConfirmEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificatorClient) SendPasswordResetEmail(ctx context.Context, in *SendPasswordResetEmailRequest, opts ...grpc.CallOption) (*SendPasswordResetEmailReply, error) {
	out := new(SendPasswordResetEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notificator/SendPasswordResetEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificatorClient) SendWelcomeEmail(ctx context.Context, in *SendWelcomeEmailRequest, opts ...grpc.CallOption) (*SendWelcomeEmailReply, error) {
	out := new(SendWelcomeEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notificator/SendWelcomeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificatorServer is the server API for Notificator service.
type NotificatorServer interface {
	SendConfirmEmail(context.Context, *SendConfirmEmailRequest) (*SendConfirmEmailReply, error)
	SendPasswordResetEmail(context.Context, *SendPasswordResetEmailRequest) (*SendPasswordResetEmailReply, error)
	SendWelcomeEmail(context.Context, *SendWelcomeEmailRequest) (*SendWelcomeEmailReply, error)
}

// UnimplementedNotificatorServer can be embedded to have forward compatible implementations.
type UnimplementedNotificatorServer struct {
}

func (*UnimplementedNotificatorServer) SendConfirmEmail(ctx context.Context, req *SendConfirmEmailRequest) (*SendConfirmEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendConfirmEmail not implemented")
}
func (*UnimplementedNotificatorServer) SendPasswordResetEmail(ctx context.Context, req *SendPasswordResetEmailRequest) (*SendPasswordResetEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPasswordResetEmail not implemented")
}
func (*UnimplementedNotificatorServer) SendWelcomeEmail(ctx context.Context, req *SendWelcomeEmailRequest) (*SendWelcomeEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWelcomeEmail not implemented")
}

func RegisterNotificatorServer(s *grpc.Server, srv NotificatorServer) {
	s.RegisterService(&_Notificator_serviceDesc, srv)
}

func _Notificator_SendConfirmEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendConfirmEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificatorServer).SendConfirmEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notificator/SendConfirmEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificatorServer).SendConfirmEmail(ctx, req.(*SendConfirmEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notificator_SendPasswordResetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPasswordResetEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificatorServer).SendPasswordResetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notificator/SendPasswordResetEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificatorServer).SendPasswordResetEmail(ctx, req.(*SendPasswordResetEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notificator_SendWelcomeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWelcomeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificatorServer).SendWelcomeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notificator/SendWelcomeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificatorServer).SendWelcomeEmail(ctx, req.(*SendWelcomeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notificator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Notificator",
	HandlerType: (*NotificatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendConfirmEmail",
			Handler:    _Notificator_SendConfirmEmail_Handler,
		},
		{
			MethodName: "SendPasswordResetEmail",
			Handler:    _Notificator_SendPasswordResetEmail_Handler,
		},
		{
			MethodName: "SendWelcomeEmail",
			Handler:    _Notificator_SendWelcomeEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notificator.proto",
}
