// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	"context"
	endpoint "github.com/alexmeli100/remit/payment/pkg/endpoint"
	paymentTran "github.com/alexmeli100/remit/payment/pkg/grpc"
	"github.com/alexmeli100/remit/payment/pkg/grpc/pb"
	log "github.com/go-kit/kit/log"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	grpcTrans "github.com/go-kit/kit/transport/grpc"
	stdopentracing "github.com/opentracing/opentracing-go"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"net"
)

type PaymentServerOpt = map[string][]grpcTrans.ServerOption
type PaymentServerOptFunc = func(opt PaymentServerOpt)

func createService(endpoints endpoint.Endpoints, opts ...PaymentServerOptFunc) *grpc.Server {
	serverOptions := make(PaymentServerOpt)

	for _, f := range opts {
		f(serverOptions)
	}

	grpcServer := paymentTran.NewGRPCServer(endpoints, serverOptions)
	baseServer := grpc.NewServer()
	pb.RegisterPaymentServer(baseServer, grpcServer)

	return baseServer
}

func runServer(ctx context.Context, server *grpc.Server) error {
	grpcListener, err := net.Listen("tcp", grpcAddr)
	errc := make(chan error, 1)

	if err != nil {
		return err
	}

	go func() {
		if err = server.Serve(grpcListener); err != nil {
			errc <- err
		}
	}()

	select {
	case <-ctx.Done():
		server.GracefulStop()
	case err := <-errc:
		return errors.Wrap(err, "listen error")
	}

	return nil
}

// add a logger to the server endpoints
func withLogger(logger log.Logger, endpoints ...string) PaymentServerOptFunc {
	return func(m map[string][]grpcTrans.ServerOption) {
		for _, ep := range endpoints {
			e, ok := m[ep]

			if !ok {
				e = make([]grpcTrans.ServerOption, 0, 2)
			}

			m[ep] = append(e, grpcTrans.ServerErrorLogger(logger))
		}
	}
}

// add a tracer to the server endpoints
func withTracer(tracer stdopentracing.Tracer, logger log.Logger, endpoints ...string) PaymentServerOptFunc {
	return func(m PaymentServerOpt) {
		for _, ep := range endpoints {
			e, ok := m[ep]

			if !ok {
				e = make([]grpcTrans.ServerOption, 0, 2)
			}

			m[ep] = append(e, grpcTrans.ServerBefore(opentracing.GRPCToContext(tracer, ep, logger)))
		}
	}
}
