apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    svc: user-service
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: user-service
      app: postgres
  template:
    metadata:
      labels:
        svc: user-service
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.1-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: database-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-db
spec:
  ports:
    - port: 5432
  selector:
    svc: user-service
    app: postgres