apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: default
data:
  POSTGRES_DB: "wealow-users-test"
  POSTGRES_USER: "doadmin"
  USER_DB_SERVICE_HOST: "db-postgresql-nyc1-31181-do-user-8015056-0.b.db.ondigitalocean.com"
  USER_DB_SERVICE_PORT: "25060"