apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
  labels:
    svc: user
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: user
      app: manager
  template:
    metadata:
      labels:
        svc: user
        app: manager
    spec:
      containers:
        - name: user-manager
          imagePullPolicy: Always
          image: alexmeli/wealow-users:0.0
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: database-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: database-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: user-manager
spec:
  type: NodePort
  ports:
    - port: 8081
  selector:
    svc: user
    app: manager


