version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wealow
      working_directory: ~/remit
      steps:
        - checkout
        - run:
            name: Get all dependencies
            command: |
              go get ./...
        - run:
            name: Run tests
            command: go test ./...
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: build and push Docker images
            shell: /bin/bash
            command: |
              chmod +x ./build.sh
              ./build.sh