version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wealow
    working_directory: /go/src/github.com/alexmeli100/remit
    steps:
      - checkout
      - run:
          name: Get all dependencies
          command: |
            go get -u ./...
      - run:
          name: Waiting for postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run tests
          command: go test ./...
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: build and push Docker images
          shell: /bin/bash
          command: |
            chmod +x ./build.sh
            ./build.sh