apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    svc: gateway
    app: wealow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: gateway
      app: wealow
  template:
    metadata:
      labels:
        svc: gateway
        app: wealow
    spec:
      containers:
        - name: gateway
          image: alexmeli/wealow-gateway:0.0
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  ports:
    - port: 5000
  selector:
    svc: gateway
    app: wealow
