apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    svc: gateway
    app: wealow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: gateway
      app: wealow
  template:
    metadata:
      labels:
        svc: gateway
        app: wealow
    spec:
      containers:
      - name: gateway
        imagePullPolicy: Always
        image: alexmeli/wealow-gateway:0.0
        ports:
        - containerPort: 8083
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: redis-password
                name: redis-password-secret
        envFrom:
          - configMapRef:
              name: gateway-config
        volumeMounts:
        - name: secret-volume
          mountPath: "/opt/firebase"
          readOnly: true
      volumes:
       - name: secret-volume
         secret:
           secretName: wealow-test-firebase
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8083
  selector:
    svc: gateway
    app: wealow

