// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/alexmeli100/remit/users/pkg/endpoint"
	pb "github.com/alexmeli100/remit/users/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	create         grpc.Handler
	getUserByID    grpc.Handler
	getUserByEmail grpc.Handler
	updateEmail    grpc.Handler
	updatePassword grpc.Handler
	updateStatus   grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.UsersServer {
	return &grpcServer{
		create:         makeCreateHandler(endpoints, options["Create"]),
		getUserByEmail: makeGetUserByEmailHandler(endpoints, options["GetUserByEmail"]),
		getUserByID:    makeGetUserByIDHandler(endpoints, options["GetUserByID"]),
		updateEmail:    makeUpdateEmailHandler(endpoints, options["UpdateEmail"]),
		updatePassword: makeUpdatePasswordHandler(endpoints, options["UpdatePassword"]),
		updateStatus:   makeUpdateStatusHandler(endpoints, options["UpdateStatus"]),
	}
}
