// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/alexmeli100/remit/payment/pkg/endpoint"
	pb "github.com/alexmeli100/remit/payment/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	saveCard               grpc.Handler
	getPaymentIntentSecret grpc.Handler
	capturePayment         grpc.Handler
	getCustomerID          grpc.Handler
	createTransaction      grpc.Handler
	getTransactions        grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.PaymentServer {
	return &grpcServer{
		getPaymentIntentSecret: makeGetPaymentIntentSecretHandler(endpoints, options[endpoint.GetPaymentIntentSecret]),
		saveCard:               makeSaveCardHandler(endpoints, options[endpoint.SaveCard]),
		capturePayment:         makeCapturePaymentHandler(endpoints, options[endpoint.CapturePayment]),
		getCustomerID:          makeGetCustomerIDHandler(endpoints, options[endpoint.GetCustomerID]),
		createTransaction:      makeCreateTransactionHandler(endpoints, options[endpoint.GetCustomerID]),
		getTransactions:        makeGetTransactionsHandler(endpoints, options[endpoint.GetTransactions]),
	}
}
