// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	"github.com/alexmeli100/remit/transfer/pkg/service"
	"github.com/go-kit/kit/endpoint"
)

const (
	// list of endpoints
	Transfer = "Transfer"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	TransferEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.TransferService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{TransferEndpoint: MakeTransferEndpoint(s)}
	for _, m := range mdw[Transfer] {
		eps.TransferEndpoint = m(eps.TransferEndpoint)
	}
	return eps
}

func GetEndpointList() []string {
	return []string{
		Transfer,
	}
}
