apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-manager
  labels:
    svc: transfer
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transfer
      app: manager
  template:
    metadata:
      labels:
        svc: transfer
        app: manager
    spec:
      containers:
        - name: transfer-manager
          imagePullPolicy: Always
          image: alexmeli/wealow-transfer:0.0
          ports:
            - containerPort: 8085
          env:
            - name: MOMO_API_KEY
              valueFrom:
                secretKeyRef:
                  key: MOMO_API_KEY
                  name: transfer-credentials
            - name: MOMO_USER_ID
              valueFrom:
                secretKeyRef:
                  key: MOMO_USER_ID
                  name: transfer-credentials
            - name: MOMO_USER_SECRET
              valueFrom:
                secretKeyRef:
                  key: MOMO_USER_SECRET
                  name: transfer-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-manager
spec:
  type: ClusterIP
  ports:
    - port: 8085
  selector:
    svc: transfer
    app: manager